name: friendcircle
description: A social networking app for managing friend circles, events, and expenses
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # State Management
  provider: ^6.1.5
  flutter_bloc: ^8.1.6
  get: ^4.7.2

  # Local Storage
  shared_preferences: ^2.5.3

  # Chart Library
  fl_chart: ^0.68.0

  # Calendar
  table_calendar: ^3.0.9

  # File Selection
  file_picker: ^8.0.0+1

  # Date Utils
  intl: ^0.19.0

  # Permissions
  permission_handler: ^11.3.1

  # Utilities
  flutter_hooks: ^0.20.5

  # Networking
  socket_io_client: ^2.0.3+1

  # Firebase - UPDATED VERSIONS for Flutter 3.35.1 compatibility
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/appicon.png"
    background_color: "#6C63FF"
    theme_color: "#6C63FF"
  windows:
    generate: true
    image_path: "assets/icons/appicon.png"
    icon_size: 48 # min:48, max:256, default: 48