// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY_HERE',
    appId: '1:162211746751:web:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '162211746751',
    projectId: 'friendcircle-3e3ee',
    authDomain: 'friendcircle-3e3ee.firebaseapp.com',
    storageBucket: 'friendcircle-3e3ee.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE',
    appId: '1:162211746751:android:b8cd16fccce927be65470a',
    messagingSenderId: '162211746751',
    projectId: 'friendcircle-3e3ee',
    storageBucket: 'friendcircle-3e3ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE',
    appId: '1:162211746751:ios:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '162211746751',
    projectId: 'friendcircle-3e3ee',
    storageBucket: 'friendcircle-3e3ee.appspot.com',
    iosClientId: '162211746751-XXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.friendcircle.friendCircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY_HERE',
    appId: '1:162211746751:ios:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '162211746751',
    projectId: 'friendcircle-3e3ee',
    storageBucket: 'friendcircle-3e3ee.appspot.com',
    iosClientId: '162211746751-XXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.friendcircle.friendCircle',
  );
}